items:
  - icon: droplets
    description: Menține motorul în stare optimă cu schimb rapid de ulei. Folosim
      uleiuri de calitate superioară pentru performanță și durabilitate.
    title: Schimb ulei
    unavailable: false
  - icon: circle-dot
    description: Asigură siguranța pe drum cu serviciile noastre pentru roți. Oferim
      rotire, echilibrare și înlocuire anvelope de calitate.
    title: Schimb roți
    unavailable: false
  - icon: car-front
    description: Siguranța ta este prioritară. Diagnosticul complet al frânelor
      asigură oprirea eficientă a mașinii în orice situație.
    title: Diagnostic frâne
    unavailable: false
  - icon: waypoints
    description: Servicii complete pentru motorul mașinii tale. De la reparații
      minore la revizii majore, funcționarea optimă este garantată.
    title: Servicii motor
    unavailable: false
  - icon: battery-charging
    description: Asigură pornirea mașinii fără probleme. Testăm, înlocuim și
      întreținem bateria pentru a evita defecțiuni neașteptate.
    title: Servicii baterie
    unavailable: false
  - icon: wind
    description: Rămâi confortabil cu serviciul nostru de aer condiționat.
      Diagnosticăm și reparăm orice problemă a sistemului AC.
    title: Servicii AC
    unavailable: false
